//Math constants
const GRAVITATION_CONSTANT = 6.67e-11 * 10e10
const FIXED_DT = 0.016
// Planet Constants
const TRACE_LENGTH_PARTS = 10
const TRACE_LENGTH_SKIP_STEPS = 8
const EXISTING_RADIUS_MIN = 2
const MASS_GIVEAWAY_FACTOR = 0.2
// Canvas constants
const BACKGROUND_COLOR = '#010'
// Simulation constans
const PLANETS_NUMBER = 10
const PLANETS_POSITION_RANGE = 500
const PLANETS_VELOCITY_RANGE = 100
const PLANETS_RADIUS_RANGE_MIN = 1
const PLANETS_RADIUS_RANGE_MAX = 10
const PLANETS_DENSITY_RANGE_MIN = 1
const PLANETS_DENSITY_RANGE_MAX = 10
