//Math constants
const GRAVITATION_CONSTANT = 6.67e-11 * 10e10
const FIXED_DT = 0.016
// Planet Constants
const TRACE_LENGTH_PARTS = 5
const TRACE_LENGTH_SKIP_STEPS = 7
const EXISTING_RADIUS_MIN = 1
const MASS_GIVEAWAY_FACTOR = 0.27
// Canvas constants
const BACKGROUND_COLOR = '#000'
// Simulation constans
const PLANETS_NUMBER = 2
const PLANETS_POSITION_RANGE = 50
const PLANETS_VELOCITY_RANGE = 0
const PLANETS_RADIUS_RANGE_MIN = 2
const PLANETS_RADIUS_RANGE_MAX = 3
const PLANETS_DENSITY_RANGE_MIN = 1
const PLANETS_DENSITY_RANGE_MAX = 2
const INITIAL_ZOOM = 10
const MAX_ACCELERATION_MAGNITUDE = 1500
const STOP_AT_MAX_ACCELERATION_MAGNITUDE = false
const LOG_AT = 3
var MAX_ELEMENT = 0
